\PassOptionsToPackage{unicode=true}{hyperref} % options for packages loaded elsewhere
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provides euro and other symbols
\else % if luatex or xelatex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={ECN190 Homework 1 Computer Problems},
  pdfauthor={Kevin Chen (914861432) John Mayhew (914807483)},
  pdfborder={0 0 0},
  breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-2}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

% set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother


\title{ECN190 Homework 1 Computer Problems}
\author{Kevin Chen (914861432) John Mayhew (914807483)}
\date{4/3/2020}

\begin{document}
\maketitle

\hypertarget{use-davis2018.dta.}{%
\subsection{1. Use Davis2018.dta.}\label{use-davis2018.dta.}}

\hypertarget{a.-use-the-substr-and-as.numeric-function-in-r-to-generate-new-variables-representing-the-year-and-month-of-the-closing-date.}{%
\subsubsection{a. Use the substr and as.numeric function in R to
generate new variables representing the year and month of the closing
date.}\label{a.-use-the-substr-and-as.numeric-function-in-r-to-generate-new-variables-representing-the-year-and-month-of-the-closing-date.}}

\begin{verbatim}
##    ClosingDate ClosingYear ClosingMonth
## 1   2018-11-05        2018           11
## 2   2018-10-31        2018           10
## 3   2018-12-27        2018           12
## 4   2018-10-31        2018           10
## 5   2018-09-07        2018            9
## 6   2018-01-10        2018            1
## 7   2018-09-21        2018            9
## 8   2018-06-13        2018            6
## 9   2018-09-21        2018            9
## 10  2018-10-30        2018           10
\end{verbatim}

\hypertarget{b.-restrict-the-sample-to-sales-of-single-family-houses-with-close-dates-in-2018.}{%
\subsubsection{b. Restrict the sample to sales of single-family houses
with close dates in
2018.}\label{b.-restrict-the-sample-to-sales-of-single-family-houses-with-close-dates-in-2018.}}

\begin{verbatim}
##    ClosingYear SingleFamily
## 1         2018            1
## 2         2018            1
## 3         2018            1
## 4         2018            1
## 5         2018            1
## 6         2018            1
## 7         2018            1
## 8         2018            1
## 9         2018            1
## 10        2018            1
\end{verbatim}

\hypertarget{c.-draw-a-bar-plot-to-summarize-the-average-sale-price-of-houses-with-different-characteristics-of-your-choice-e.g.-bedrooms-bathrooms-closing-month-etc.-using-the-subsample-created-in-part-b.}{%
\subsubsection{c.~Draw a bar plot to summarize the average sale price of
houses with different characteristics of your choice (e.g., bedrooms,
bathrooms, closing month, etc.) using the subsample created in part
b.}\label{c.-draw-a-bar-plot-to-summarize-the-average-sale-price-of-houses-with-different-characteristics-of-your-choice-e.g.-bedrooms-bathrooms-closing-month-etc.-using-the-subsample-created-in-part-b.}}

\includegraphics{ECN190-Homework-1-Final_files/figure-latex/unnamed-chunk-4-1.pdf}

\hypertarget{d.-run-a-regression-of-sale-price-on-month-of-closing-and-test-the-overall-significance-of-the-regression-with-5-significance-level.}{%
\subsubsection{d.~Run a regression of sale price on month of closing and
test the overall significance of the regression with 5\% significance
level.}\label{d.-run-a-regression-of-sale-price-on-month-of-closing-and-test-the-overall-significance-of-the-regression-with-5-significance-level.}}

\includegraphics{ECN190-Homework-1-Final_files/figure-latex/unnamed-chunk-5-1.pdf}

\begin{verbatim}
## 
## Call:
## lm(formula = SalePrice ~ ClosingMonth, data = Davis2018)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -340025 -135369  -25100  105842  676131 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept)    741640      34595  21.438   <2e-16 ***
## ClosingMonth    -1616       4907  -0.329    0.742    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 205900 on 210 degrees of freedom
## Multiple R-squared:  0.0005159,  Adjusted R-squared:  -0.004244 
## F-statistic: 0.1084 on 1 and 210 DF,  p-value: 0.7423
\end{verbatim}

It appears that regressing Closing Month on Sale Price is not effective;
the p-value is 0.7423, far from significant at the 5\% level.

\hypertarget{e.-how-would-you-obtain-heteroskedastic-robust-standard-errors-in-the-above-regression-if-you-think-the-homoskedasticity-assumption-is-violated}{%
\subsubsection{e. How would you obtain heteroskedastic robust standard
errors in the above regression if you think the homoskedasticity
assumption is
violated?}\label{e.-how-would-you-obtain-heteroskedastic-robust-standard-errors-in-the-above-regression-if-you-think-the-homoskedasticity-assumption-is-violated}}

We would carry out the t-test to obtain heteroskadasticity robust
standard errors and their t-values.

\begin{verbatim}
## 
## t test of coefficients:
## 
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  741640.2    35131.0  21.111   <2e-16 ***
## ClosingMonth  -1615.6     5227.7  -0.309   0.7576    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\hypertarget{f.-run-a-regression-of-sale-price-on-list-price-and-days-on-market.-how-do-you-interpret-the-slope-coefficients-of-this-regression}{%
\subsubsection{f.~Run a regression of sale price on list price and days
on market. How do you interpret the slope coefficients of this
regression?}\label{f.-run-a-regression-of-sale-price-on-list-price-and-days-on-market.-how-do-you-interpret-the-slope-coefficients-of-this-regression}}

\begin{verbatim}
## 
## Call:
## lm(formula = SalePrice ~ ListPrice + DaysOnMarket, data = Davis2018)
## 
## Coefficients:
##  (Intercept)     ListPrice  DaysOnMarket  
##   21846.3185        0.9839     -385.2674
\end{verbatim}

The slope coefficients represent the increase or decrease in the
dependent variable based on values of the independent variables; in this
case, the coefficient for ListPrice (0.9839) is the increase in
SalePrice with every 1-unit increase in ListPrice, and the coefficient
for DaysOnMarket (-385.2674) is the decrease in SalePrice associated
with every 1-unit increase in DaysOnMarket.

In other words, the ListPrice is slightly lower than SalePrice at every
level, but mirrors its characteristics, while for every day on the
market, a house loses around 385 dollars in value.

\newpage

\hypertarget{do-you-think-the-zero-conditional-mean-condition-is-satisfied-here}{%
\subsubsection{Do you think the zero conditional mean condition is
satisfied
here?}\label{do-you-think-the-zero-conditional-mean-condition-is-satisfied-here}}

~ ~

\includegraphics{ECN190-Homework-1-Final_files/figure-latex/unnamed-chunk-9-1.pdf}

~ ~

From plotting the residuals, we can see on average that the zero
conditonal mean condition is satisfied because the residuals hover
between -50000 and 50000, and the expected value is constant at all
levels. There are a few outliers but on average, the residuals are 0 if
they were to be summed up, allowing us to conclude a zero conditional
mean.

\newpage

\hypertarget{g.-add-house-characteristics-to-the-above-regression-model-and-test-the-joint-significance-of-all-newly-added-house-characteristics-variables.}{%
\subsubsection{g. Add house characteristics to the above regression
model and test the joint significance of all newly added house
characteristics
variables.}\label{g.-add-house-characteristics-to-the-above-regression-model-and-test-the-joint-significance-of-all-newly-added-house-characteristics-variables.}}

\begin{verbatim}
## 
## Call:
## lm(formula = SalePrice ~ ListPrice + DaysOnMarket + Bedroom + 
##     FullBath + Stories, data = Davis2018)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -197000  -13049   -2131   11838   81446 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(>|t|)    
## (Intercept)   1.036e+04  1.070e+04   0.968   0.3343    
## ListPrice     1.006e+00  1.578e-02  63.744  < 2e-16 ***
## DaysOnMarket -3.493e+02  7.766e+01  -4.497 1.17e-05 ***
## Bedroom3      4.209e+03  8.072e+03   0.522   0.6026    
## Bedroom4     -8.933e+03  9.595e+03  -0.931   0.3530    
## Bedroom5     -2.274e+03  1.186e+04  -0.192   0.8481    
## Bedroom6     -9.588e+03  2.310e+04  -0.415   0.6785    
## Bedroom7      3.585e+04  3.359e+04   1.067   0.2872    
## FullBath2     2.428e+03  7.404e+03   0.328   0.7433    
## FullBath3     8.884e+03  1.001e+04   0.888   0.3757    
## FullBath4    -4.047e+04  1.661e+04  -2.437   0.0157 *  
## FullBath5     2.536e+04  2.570e+04   0.986   0.3251    
## Stories      -5.002e+03  5.859e+03  -0.854   0.3942    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 29190 on 199 degrees of freedom
## Multiple R-squared:  0.981,  Adjusted R-squared:  0.9798 
## F-statistic: 854.5 on 12 and 199 DF,  p-value: < 2.2e-16
\end{verbatim}

From our original regression, we added 3 house characteristics, number
of bedrooms, number of fullbaths, and stories. With p value \textless{}
2.2e-16, which is close to 0, we can conclude there is joint
significance of the newly added housing variables.

\newpage

\hypertarget{h.-review-your-ecn-102-or-sta-108-ecn-140-etc-notes-on-regressions-with-quadratic-terms.-now-add-a-quadratic-term-of-daysonmarket-to-the-regression-in-f.-for-houses-with-the-same-list-prices-what-is-the-predicted-difference-in-sale-price-if-a-house-stays-on-market-a-week-longer-than-the-other}{%
\subsubsection{h. Review your ECN 102 (or STA 108, ECN 140, etc\ldots{})
notes on regressions with quadratic terms. Now, add a quadratic term of
DaysOnMarket to the regression in f.~For houses with the same list
prices, what is the predicted difference in sale price if a house stays
on market a week longer than the
other?}\label{h.-review-your-ecn-102-or-sta-108-ecn-140-etc-notes-on-regressions-with-quadratic-terms.-now-add-a-quadratic-term-of-daysonmarket-to-the-regression-in-f.-for-houses-with-the-same-list-prices-what-is-the-predicted-difference-in-sale-price-if-a-house-stays-on-market-a-week-longer-than-the-other}}

\begin{verbatim}
## 
## Call:
## lm(formula = SalePrice ~ ListPrice + DaysOnMarket + I(DaysOnMarket^2), 
##     data = Davis2018)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -235156  -10821   -4620   12669   81425 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(>|t|)    
## (Intercept)        2.330e+04  7.358e+03   3.167  0.00177 ** 
## ListPrice          9.899e-01  1.018e-02  97.269  < 2e-16 ***
## DaysOnMarket      -9.326e+02  1.834e+02  -5.087 8.13e-07 ***
## I(DaysOnMarket^2)  4.453e+00  1.362e+00   3.269  0.00126 ** 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 29390 on 208 degrees of freedom
## Multiple R-squared:  0.9798, Adjusted R-squared:  0.9795 
## F-statistic:  3367 on 3 and 208 DF,  p-value: < 2.2e-16
\end{verbatim}

Quadratic Model: 23301.9935 + ListPrice(0.9889) +
DaysOnMarket(-932.6248) + DaysOnMarket\^{}2(4.4529)

If two houses have identical List Prices, and one stays on the market 1
week longer:

Let C = 23301.9935 + ListPrice(0.9889)

House 1 = C + 0

House 2 = C + 7\emph{(-932.6248) + 49}(4.4529) = C - 6310.182

``The house that stays on the market 7 days longer loses \$6,310.18 in
value.''

\newpage

\hypertarget{use-the-rental.dta-dataset.-this-dataset-comes-from-the-wooldridge-textbook.-it-includes-rental-prices-and-other-variables-of-64-college-towns-for-the-years-of-1980-and-1990.}{%
\subsection{2. Use the RENTAL.dta dataset. This dataset comes from the
Wooldridge textbook. It includes rental prices and other variables of 64
college towns for the years of 1980 and
1990.}\label{use-the-rental.dta-dataset.-this-dataset-comes-from-the-wooldridge-textbook.-it-includes-rental-prices-and-other-variables-of-64-college-towns-for-the-years-of-1980-and-1990.}}

\hypertarget{a.-review-your-ecn-102-or-sta-108-ecn-140-etc-notes-on-regressions-with-log-transformed-variables.-regress-log-of-rent-lrent-on-log-of-pop-lpop-log-of-avginc-lavginc-and-pctstu-using-only-1990-data.-interpret-the-slope-coefficient-of-lavginc-as-well-as-pctstu.-do-you-think-the-zero-conditional-mean-assumption-is-satisfied-here}{%
\subsubsection{a. Review your ECN 102 (or STA 108, ECN 140, etc\ldots{})
notes on regressions with log transformed variables. Regress log of rent
(lrent) on log of pop (lpop), log of avginc (lavginc), and pctstu using
only 1990 data. Interpret the slope coefficient of lavginc as well as
pctstu. Do you think the zero conditional mean assumption is satisfied
here?}\label{a.-review-your-ecn-102-or-sta-108-ecn-140-etc-notes-on-regressions-with-log-transformed-variables.-regress-log-of-rent-lrent-on-log-of-pop-lpop-log-of-avginc-lavginc-and-pctstu-using-only-1990-data.-interpret-the-slope-coefficient-of-lavginc-as-well-as-pctstu.-do-you-think-the-zero-conditional-mean-assumption-is-satisfied-here}}

\begin{verbatim}
## 
## Call:
## lm(formula = lrent ~ lpop + lavginc + pctstu, data = rental1990)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.22706 -0.09469 -0.02827  0.03806  0.48271 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 0.042780   0.843875   0.051    0.960    
## lpop        0.065868   0.038826   1.696    0.095 .  
## lavginc     0.507015   0.080836   6.272 4.29e-08 ***
## pctstu      0.005630   0.001742   3.232    0.002 ** 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.1512 on 60 degrees of freedom
## Multiple R-squared:  0.4579, Adjusted R-squared:  0.4308 
## F-statistic: 16.89 on 3 and 60 DF,  p-value: 4.541e-08
\end{verbatim}

Since this model is a log regression, we can interpret the coefficients
as percentages/elasticities. If we change lavginc (log of average
income) by 1\%, we would expect rent to change by 0.5\%. However, for
pctstu (percentage of student), we did not take the log of it since it
is in percentages already. So if we change pctstu by 1 unit (\% in this
case), we would expect rent to change by 0.563\%.

\includegraphics{ECN190-Homework-1-Final_files/figure-latex/unnamed-chunk-16-1.pdf}

For this model, it does not seem that the zero conditional mean
assumption is satisfied here as the majority of the residuals are
negative which means on average, the mean of the residuals is not zero.

\hypertarget{b.-the-variable-clrent-only-has-non-missing-values-in-1990.-verify-those-values-are-equal-to-the-change-in-lrent-in-each-city-between-year-1980-and-year-1990.-recall-that-changes-in-log-transformed-variables-could-be-interpreted-as-changes-in-the-original-variable.-notice-that-clrent-is-equal-to-.5516071-for-city-1.-how-do-you-interpret-this-number}{%
\subsubsection{b. The variable clrent only has non-missing values in
1990. Verify those values are equal to the change in lrent in each city
between year 1980 and year 1990. Recall that changes in log transformed
variables could be interpreted as \% changes in the original variable.
Notice that clrent is equal to .5516071 for city 1. How do you interpret
this
number?}\label{b.-the-variable-clrent-only-has-non-missing-values-in-1990.-verify-those-values-are-equal-to-the-change-in-lrent-in-each-city-between-year-1980-and-year-1990.-recall-that-changes-in-log-transformed-variables-could-be-interpreted-as-changes-in-the-original-variable.-notice-that-clrent-is-equal-to-.5516071-for-city-1.-how-do-you-interpret-this-number}}

For city 1, the clrent is equal to 0.5516071. This means that in city 1,
the rent in 1990 was 55.16\% higher than it was in 1980, or there was a
55.16\% change in rent from 1980 to 1990.

\begin{verbatim}
##    city year    clrent    lrent rent clrent.calc
## 2     1   90 0.5516071 5.834811  342   0.5516071
## 4     2   90 0.4289236 6.206576  496   0.4289236
## 6     3   90 0.4855080 5.860786  351   0.4855080
## 8     4   90 0.7894783 6.376727  588   0.7894783
## 10    5   90 0.6664791 6.829794  925   0.6664791
## 12    6   90 0.8253188 6.445720  630   0.8253188
## 14    7   90 0.5453234 6.255750  521   0.5453234
## 16    8   90 0.4959292 6.045005  422   0.4959292
## 18    9   90 0.8087320 6.342122  568   0.8087320
## 20   10   90 0.4590969 5.948035  383   0.4590969
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{all}\NormalTok{(rentaldata2b.omit}\OperatorTok{$}\NormalTok{clrent }\OperatorTok{==}\StringTok{ }\NormalTok{rentaldata2b.omit}\OperatorTok{$}\NormalTok{clrent.calc)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] TRUE
\end{verbatim}

\hypertarget{c.-finally-we-regress-change-in-lrent-clrent-on-change-in-lpop-clpop-change-in-lavginc-clavginc-and-change-in-pctstu-cpctstu-between-year-1980-and-year-1990.-how-do-you-interpret-the-intercept-here-explain-what-the-zero-conditional-mean-assumption-is-requiring-in-this-regression.}{%
\subsubsection{c.~Finally, we regress change in lrent (clrent) on change
in lpop (clpop), change in lavginc (clavginc), and change in pctstu
(cpctstu) between year 1980 and year 1990. How do you interpret the
intercept here? Explain what the zero conditional mean assumption is
requiring in this
regression.}\label{c.-finally-we-regress-change-in-lrent-clrent-on-change-in-lpop-clpop-change-in-lavginc-clavginc-and-change-in-pctstu-cpctstu-between-year-1980-and-year-1990.-how-do-you-interpret-the-intercept-here-explain-what-the-zero-conditional-mean-assumption-is-requiring-in-this-regression.}}

\begin{verbatim}
## 
## Call:
## lm(formula = clrent ~ clpop + clavginc + cpctstu, data = rentaldata.omit)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.18697 -0.06216 -0.01438  0.05518  0.23783 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 0.385521   0.036824  10.469 3.66e-15 ***
## clpop       0.072246   0.088343   0.818  0.41671    
## clavginc    0.309961   0.066477   4.663 1.79e-05 ***
## cpctstu     0.011203   0.004132   2.711  0.00873 ** 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.09013 on 60 degrees of freedom
## Multiple R-squared:  0.3223, Adjusted R-squared:  0.2884 
## F-statistic:  9.51 on 3 and 60 DF,  p-value: 3.136e-05
\end{verbatim}

The intercept (0.385521) is the percent change in rent that would occur
without any change in population, average income, or percentage of
students; even if nothing else in the model changes, the rent would
still increase by around 38.5\%.

In the context of this regression, the zero conditional mean assumption
requires that the expected differnence between the actual percent change
in rent and the predicted percent change in rent based on our variables
has a mean of 0, meaning that the residual plot of the errors should be
randomly distributed about the y-intercept.

\includegraphics{ECN190-Homework-1-Final_files/figure-latex/unnamed-chunk-21-1.pdf}

~ ~

It appears from the plot that the zero-conditional mean is satisfied.
The majority of the residuals hover between -0.2 and 0.2, so on average,
the sum of the residuals equate to zero. This leads us to the conclusion
that the zero-conditional mean is satisfied from looking at the residual
plot.

\hypertarget{appendix}{%
\subsubsection{Appendix}\label{appendix}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(readstata13)}
\KeywordTok{library}\NormalTok{(dplyr)}
\KeywordTok{library}\NormalTok{(ggplot2)}
\KeywordTok{library}\NormalTok{(ggpubr)}
\KeywordTok{library}\NormalTok{(lmtest)}
\KeywordTok{library}\NormalTok{(sandwich)}
\KeywordTok{library}\NormalTok{(ggthemes)}
\KeywordTok{library}\NormalTok{(knitr)}
\NormalTok{Davis2018 =}\StringTok{ }\KeywordTok{read.dta13}\NormalTok{(}\StringTok{"Davis2018.dta"}\NormalTok{)}
\NormalTok{Davis2018}\OperatorTok{$}\NormalTok{ClosingYear <-}\StringTok{ }\KeywordTok{as.numeric}\NormalTok{(}\KeywordTok{substr}\NormalTok{(Davis2018}\OperatorTok{$}\NormalTok{ClosingDate,}\DecValTok{1}\NormalTok{,}\DecValTok{4}\NormalTok{))}
\NormalTok{Davis2018}\OperatorTok{$}\NormalTok{ClosingMonth <-}\StringTok{ }\KeywordTok{as.numeric}\NormalTok{(}\KeywordTok{substr}\NormalTok{(Davis2018}\OperatorTok{$}\NormalTok{ClosingDate,}\DecValTok{6}\NormalTok{,}\DecValTok{7}\NormalTok{))}
\NormalTok{p1a.output =}\StringTok{ }
\StringTok{  }\NormalTok{Davis2018 }\OperatorTok{%>%}\StringTok{ }\KeywordTok{select}\NormalTok{(ClosingDate, ClosingYear, ClosingMonth)}
\KeywordTok{head}\NormalTok{(p1a.output, }\DecValTok{10}\NormalTok{)}

\NormalTok{Davis2018 =}\StringTok{ }\KeywordTok{filter}\NormalTok{(Davis2018, ClosingYear }\OperatorTok{==}\StringTok{ }\DecValTok{2018} \OperatorTok{&}\StringTok{ }\NormalTok{SingleFamily }\OperatorTok{==}\StringTok{ }\DecValTok{1}\NormalTok{)}
\NormalTok{p2a.output =}\StringTok{ }
\StringTok{  }\NormalTok{Davis2018 }\OperatorTok{%>%}\StringTok{ }\KeywordTok{select}\NormalTok{(ClosingYear, SingleFamily)}
\KeywordTok{head}\NormalTok{(p2a.output, }\DecValTok{10}\NormalTok{)}

\NormalTok{Davis2018}\OperatorTok{$}\NormalTok{Bedroom =}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(Davis2018}\OperatorTok{$}\NormalTok{Bedroom)}
\NormalTok{tab =}\StringTok{ }\NormalTok{Davis2018 }\OperatorTok{%>%}\StringTok{ }\KeywordTok{group_by}\NormalTok{(Bedroom) }\OperatorTok{%>%}\StringTok{ }\KeywordTok{summarise}\NormalTok{(}\KeywordTok{mean}\NormalTok{(SalePrice))}
\NormalTok{tab =}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(tab)}

\KeywordTok{names}\NormalTok{(tab) =}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"NumberBedrooms"}\NormalTok{, }\StringTok{"AvgSale"}\NormalTok{)}
\NormalTok{pl =}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ tab, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ NumberBedrooms, }\DataTypeTok{y =}\NormalTok{ AvgSale)) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"identity"}\NormalTok{, }\DataTypeTok{width =} \KeywordTok{I}\NormalTok{(}\DecValTok{1}\OperatorTok{/}\DecValTok{3}\NormalTok{), }\DataTypeTok{color =} \StringTok{"black"}\NormalTok{, }\DataTypeTok{fill =} \StringTok{"#F7CAC9"}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{theme_bw}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{scale_x_discrete}\NormalTok{(}\StringTok{"Number of Bedrooms"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_y_continuous}\NormalTok{(}\StringTok{"Average Sale Price"}\NormalTok{, }\DataTypeTok{breaks =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{250000}\NormalTok{, }\DecValTok{500000}\NormalTok{, }\DecValTok{750000}\NormalTok{, }\DecValTok{1000000}\NormalTok{, }\DecValTok{1250000}\NormalTok{, }\DecValTok{1500000}\NormalTok{), }\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1570000}\NormalTok{)) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Avg. Sale Price by Bedrooms"}\NormalTok{)}

\NormalTok{Davis2018}\OperatorTok{$}\NormalTok{FullBath =}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(Davis2018}\OperatorTok{$}\NormalTok{FullBath)}
\NormalTok{tab =}\StringTok{ }\NormalTok{Davis2018 }\OperatorTok{%>%}\StringTok{ }\KeywordTok{group_by}\NormalTok{(FullBath) }\OperatorTok{%>%}\StringTok{ }\KeywordTok{summarise}\NormalTok{(}\KeywordTok{mean}\NormalTok{(SalePrice))}
\NormalTok{tab =}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(tab)}

\KeywordTok{names}\NormalTok{(tab) =}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"NumberFullBaths"}\NormalTok{, }\StringTok{"AvgSale"}\NormalTok{)}
\NormalTok{pl2 =}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ tab, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ NumberFullBaths, }\DataTypeTok{y =}\NormalTok{ AvgSale)) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"identity"}\NormalTok{, }\DataTypeTok{width =} \KeywordTok{I}\NormalTok{(}\DecValTok{1}\OperatorTok{/}\DecValTok{5}\NormalTok{), }\DataTypeTok{color =} \StringTok{"black"}\NormalTok{, }\DataTypeTok{fill =} \StringTok{"#F7CAC9"}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{theme_bw}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{scale_x_discrete}\NormalTok{(}\StringTok{"Number of Full Bathrooms"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_y_continuous}\NormalTok{(}\StringTok{"Average Sale Price"}\NormalTok{, }\DataTypeTok{breaks =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{250000}\NormalTok{, }\DecValTok{500000}\NormalTok{, }\DecValTok{750000}\NormalTok{, }\DecValTok{1000000}\NormalTok{, }
                                                      \DecValTok{1250000}\NormalTok{, }\DecValTok{1500000}\NormalTok{), }\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1570000}\NormalTok{)) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Avg. Sale Price by Bathrooms"}\NormalTok{)}

\NormalTok{Davis2018}\OperatorTok{$}\NormalTok{ClosingMonth =}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(Davis2018}\OperatorTok{$}\NormalTok{ClosingMonth)}
\NormalTok{tab =}\StringTok{ }\NormalTok{Davis2018 }\OperatorTok{%>%}\StringTok{ }\KeywordTok{group_by}\NormalTok{(ClosingMonth) }\OperatorTok{%>%}\StringTok{ }\KeywordTok{summarise}\NormalTok{(}\KeywordTok{mean}\NormalTok{(SalePrice))}
\NormalTok{tab =}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(tab)}

\KeywordTok{names}\NormalTok{(tab) =}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"NumberClosingMonths"}\NormalTok{, }\StringTok{"AvgSale"}\NormalTok{)}
\NormalTok{pl3 =}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ tab, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ NumberClosingMonths, }\DataTypeTok{y =}\NormalTok{ AvgSale)) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"identity"}\NormalTok{, }\DataTypeTok{width =} \KeywordTok{I}\NormalTok{(}\DecValTok{1}\OperatorTok{/}\DecValTok{5}\NormalTok{), }\DataTypeTok{color =} \StringTok{"black"}\NormalTok{, }\DataTypeTok{fill =} \StringTok{"#F7CAC9"}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{theme_bw}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{scale_x_discrete}\NormalTok{(}\StringTok{"Month"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_y_continuous}\NormalTok{(}\StringTok{"Average Sale Price"}\NormalTok{, }\DataTypeTok{breaks =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{250000}\NormalTok{, }\DecValTok{500000}\NormalTok{, }\DecValTok{750000}\NormalTok{, }\DecValTok{1000000}\NormalTok{), }\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1050000}\NormalTok{)) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Avg. Sale Price by Month"}\NormalTok{)}

\NormalTok{Davis2018}\OperatorTok{$}\NormalTok{Areacode =}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(Davis2018}\OperatorTok{$}\NormalTok{Areacode)}
\NormalTok{tab =}\StringTok{ }\NormalTok{Davis2018 }\OperatorTok{%>%}\StringTok{ }\KeywordTok{group_by}\NormalTok{(Areacode) }\OperatorTok{%>%}\StringTok{ }\KeywordTok{summarise}\NormalTok{(}\KeywordTok{mean}\NormalTok{(SalePrice))}
\NormalTok{tab =}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(tab)}

\KeywordTok{names}\NormalTok{(tab) =}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"NumberAreacodes"}\NormalTok{, }\StringTok{"AvgSale"}\NormalTok{)}
\NormalTok{pl4 =}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ tab, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ NumberAreacodes, }\DataTypeTok{y =}\NormalTok{ AvgSale)) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"identity"}\NormalTok{, }\DataTypeTok{width =} \KeywordTok{I}\NormalTok{(}\DecValTok{1}\OperatorTok{/}\DecValTok{7}\NormalTok{), }\DataTypeTok{color =} \StringTok{"black"}\NormalTok{, }\DataTypeTok{fill =} \StringTok{"#F7CAC9"}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{theme_bw}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{scale_x_discrete}\NormalTok{(}\StringTok{"Area Code"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_y_continuous}\NormalTok{(}\StringTok{"Average Sale Price"}\NormalTok{, }\DataTypeTok{breaks =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{250000}\NormalTok{, }\DecValTok{500000}\NormalTok{, }\DecValTok{750000}\NormalTok{, }\DecValTok{1000000}\NormalTok{), }\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1050000}\NormalTok{)) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Avg. Sale Price by Area Code"}\NormalTok{)}

\KeywordTok{ggarrange}\NormalTok{(pl, pl2, pl3, pl4, }\DataTypeTok{ncol =} \DecValTok{2}\NormalTok{, }\DataTypeTok{nrow =} \DecValTok{2}\NormalTok{)}
\NormalTok{Davis2018}\OperatorTok{$}\NormalTok{ClosingMonth =}\StringTok{ }\KeywordTok{as.double}\NormalTok{(Davis2018}\OperatorTok{$}\NormalTok{ClosingMonth)}
\NormalTok{lm.model =}\StringTok{ }\KeywordTok{lm}\NormalTok{(SalePrice }\OperatorTok{~}\StringTok{ }\NormalTok{ClosingMonth, }\DataTypeTok{data =}\NormalTok{ Davis2018)}
\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ Davis2018, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ ClosingMonth, }\DataTypeTok{y =}\NormalTok{ SalePrice)) }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_point}\NormalTok{() }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme_bw}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{scale_x_continuous}\NormalTok{(}\StringTok{"Closing Month"}\NormalTok{, }\DataTypeTok{breaks =} \KeywordTok{seq}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{12}\NormalTok{, }\DecValTok{1}\NormalTok{), }\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\FloatTok{0.75}\NormalTok{, }\FloatTok{12.25}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_y_continuous}\NormalTok{(}\StringTok{"Sale Price"}\NormalTok{, }\DataTypeTok{breaks =} \KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1500000}\NormalTok{, }\DataTypeTok{by =} \DecValTok{150000}\NormalTok{), }\DataTypeTok{limits =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1550000}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_smooth}\NormalTok{(}\DataTypeTok{method =} \StringTok{"lm"}\NormalTok{, }\DataTypeTok{se =}\NormalTok{ F, }\DataTypeTok{formula =} \StringTok{"y ~ x"}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Closing Month versus Sale Price"}\NormalTok{)}

\KeywordTok{summary}\NormalTok{(lm.model)}
\KeywordTok{coeftest}\NormalTok{(lm.model, }\DataTypeTok{vcov =}\NormalTok{ sandwich)}
\NormalTok{Davis2018}\OperatorTok{$}\NormalTok{DaysOnMarket =}\StringTok{ }\KeywordTok{as.double}\NormalTok{(Davis2018}\OperatorTok{$}\NormalTok{DaysOnMarket)}
\NormalTok{Davis2018}\OperatorTok{$}\NormalTok{ListPrice =}\StringTok{ }\KeywordTok{as.double}\NormalTok{(Davis2018}\OperatorTok{$}\NormalTok{ListPrice)}
\NormalTok{lm.model2 =}\StringTok{ }\KeywordTok{lm}\NormalTok{(SalePrice }\OperatorTok{~}\StringTok{ }\NormalTok{ListPrice }\OperatorTok{+}\StringTok{ }\NormalTok{DaysOnMarket, }\DataTypeTok{data =}\NormalTok{ Davis2018)}
\KeywordTok{print}\NormalTok{(lm.model2)}
\KeywordTok{cat}\NormalTok{(}\StringTok{"}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{newpage"}\NormalTok{)}
\NormalTok{df1 =}\StringTok{ }\NormalTok{Davis2018 }\OperatorTok{%>%}\StringTok{ }\KeywordTok{select}\NormalTok{(ListPrice, DaysOnMarket, SalePrice)}
\NormalTok{df =}\StringTok{ }\KeywordTok{cbind.data.frame}\NormalTok{(df1, lm.model2}\OperatorTok{$}\NormalTok{residuals, lm.model2}\OperatorTok{$}\NormalTok{fitted.values)}
\NormalTok{df =}\StringTok{ }
\StringTok{  }\NormalTok{df }\OperatorTok{%>%}\StringTok{ }\KeywordTok{arrange}\NormalTok{(}\StringTok{`}\DataTypeTok{lm.model2$fitted.values}\StringTok{`}\NormalTok{) }\CommentTok{#%>% select()}
\NormalTok{df}\OperatorTok{$}\NormalTok{Index =}\StringTok{ }\DecValTok{1}\OperatorTok{:}\KeywordTok{nrow}\NormalTok{(df)}
\NormalTok{df =}\StringTok{ }
\StringTok{  }\NormalTok{df }\OperatorTok{%>%}\StringTok{ }\KeywordTok{select}\NormalTok{(Index, }\StringTok{`}\DataTypeTok{lm.model2$residuals}\StringTok{`}\NormalTok{)}
\KeywordTok{names}\NormalTok{(df) =}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Index"}\NormalTok{, }\StringTok{"Residuals"}\NormalTok{)}
\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ df, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ Index, }\DataTypeTok{y =}\NormalTok{ Residuals)) }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_point}\NormalTok{() }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{theme_clean}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_hline}\NormalTok{(}\DataTypeTok{yintercept =} \DecValTok{0}\NormalTok{, }\DataTypeTok{linetype =} \StringTok{"dashed"}\NormalTok{) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{scale_x_continuous}\NormalTok{(}\StringTok{""}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Residual Plot"}\NormalTok{)}
\KeywordTok{cat}\NormalTok{(}\StringTok{"}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{newpage"}\NormalTok{)}
\NormalTok{lm.model3 =}\StringTok{ }\KeywordTok{lm}\NormalTok{(SalePrice }\OperatorTok{~}\StringTok{ }\NormalTok{ListPrice }\OperatorTok{+}\StringTok{ }\NormalTok{DaysOnMarket }\OperatorTok{+}\StringTok{ }\NormalTok{Bedroom }\OperatorTok{+}\StringTok{ }\NormalTok{FullBath }\OperatorTok{+}\StringTok{ }\NormalTok{Stories, }\DataTypeTok{data =}\NormalTok{ Davis2018)}
\KeywordTok{summary}\NormalTok{(lm.model3)}
\KeywordTok{cat}\NormalTok{(}\StringTok{"}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{newpage"}\NormalTok{)}
\NormalTok{lm.model4 =}\StringTok{ }\KeywordTok{lm}\NormalTok{(SalePrice }\OperatorTok{~}\StringTok{ }\NormalTok{ListPrice }\OperatorTok{+}\StringTok{ }\NormalTok{DaysOnMarket }\OperatorTok{+}\StringTok{ }\KeywordTok{I}\NormalTok{(DaysOnMarket}\OperatorTok{^}\DecValTok{2}\NormalTok{), }\DataTypeTok{data =}\NormalTok{ Davis2018)}
\KeywordTok{summary}\NormalTok{(lm.model4)}
\KeywordTok{cat}\NormalTok{(}\StringTok{"}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{newpage"}\NormalTok{)}
\NormalTok{rentaldata <-}\StringTok{ }\KeywordTok{read.dta13}\NormalTok{(}\StringTok{"RENTAL.DTA"}\NormalTok{)}

\NormalTok{rental1990 <-}\StringTok{ }\KeywordTok{subset}\NormalTok{(rentaldata, year }\OperatorTok{!=}\StringTok{ }\DecValTok{80}\NormalTok{)}

\NormalTok{model2 <-}\StringTok{ }\KeywordTok{lm}\NormalTok{(lrent }\OperatorTok{~}\StringTok{ }\NormalTok{lpop }\OperatorTok{+}\StringTok{ }\NormalTok{lavginc }\OperatorTok{+}\StringTok{ }\NormalTok{pctstu, }\DataTypeTok{data =}\NormalTok{ rental1990)}
\KeywordTok{summary}\NormalTok{(model2)}
\NormalTok{df2 <-}\StringTok{ }\NormalTok{rental1990 }\OperatorTok{%>%}\StringTok{ }\KeywordTok{select}\NormalTok{(lpop, lavginc, pctstu, lrent)}
\NormalTok{df2}\FloatTok{.1}\NormalTok{ <-}\StringTok{ }\KeywordTok{cbind.data.frame}\NormalTok{(df2, model2}\OperatorTok{$}\NormalTok{residuals, model2}\OperatorTok{$}\NormalTok{fitted.values)}
\NormalTok{df2}\FloatTok{.1}\NormalTok{ <-}\StringTok{ }
\StringTok{  }\NormalTok{df2}\FloatTok{.1} \OperatorTok{%>%}\StringTok{ }\KeywordTok{arrange}\NormalTok{(}\StringTok{`}\DataTypeTok{model2$fitted.values}\StringTok{`}\NormalTok{) }\CommentTok{#%>% select()}
\NormalTok{df2}\FloatTok{.1}\OperatorTok{$}\NormalTok{Index <-}\StringTok{ }\DecValTok{1}\OperatorTok{:}\KeywordTok{nrow}\NormalTok{(df2}\FloatTok{.1}\NormalTok{)}
\NormalTok{df2}\FloatTok{.1}\NormalTok{ <-}\StringTok{ }
\StringTok{  }\NormalTok{df2}\FloatTok{.1} \OperatorTok{%>%}\StringTok{ }\KeywordTok{select}\NormalTok{(Index, }\StringTok{`}\DataTypeTok{model2$residuals}\StringTok{`}\NormalTok{)}
\KeywordTok{names}\NormalTok{(df2}\FloatTok{.1}\NormalTok{) =}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Index"}\NormalTok{, }\StringTok{"Residuals"}\NormalTok{)}
\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ df2}\FloatTok{.1}\NormalTok{, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ Index, }\DataTypeTok{y =}\NormalTok{ Residuals)) }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_point}\NormalTok{() }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{theme_clean}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_hline}\NormalTok{(}\DataTypeTok{yintercept =} \DecValTok{0}\NormalTok{, }\DataTypeTok{linetype =} \StringTok{"dashed"}\NormalTok{) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{scale_x_continuous}\NormalTok{(}\StringTok{""}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Residual Plot"}\NormalTok{)}
\NormalTok{rentaldata2b =}\StringTok{ }
\StringTok{  }\NormalTok{rentaldata }\OperatorTok{%>%}\StringTok{ }\KeywordTok{select}\NormalTok{(city, year, clrent, lrent, rent)}

\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\OperatorTok{:}\KeywordTok{nrow}\NormalTok{(rentaldata2b))\{}
  \ControlFlowTok{if}\NormalTok{ (i }\OperatorTok{%%}\StringTok{ }\DecValTok{2} \OperatorTok{==}\StringTok{ }\DecValTok{0}\NormalTok{)\{}
\NormalTok{    rentaldata2b}\OperatorTok{$}\NormalTok{clrent.calc[i] =}\StringTok{ }\NormalTok{rentaldata2b}\OperatorTok{$}\NormalTok{lrent[i] }\OperatorTok{-}\StringTok{ }\NormalTok{rentaldata2b}\OperatorTok{$}\NormalTok{lrent[i}\DecValTok{-1}\NormalTok{]}
    
\NormalTok{  \} }\ControlFlowTok{else}\NormalTok{\{}
\NormalTok{    rentaldata2b}\OperatorTok{$}\NormalTok{clrent.calc[i] =}\StringTok{ }\DecValTok{0}
\NormalTok{  \}}
\NormalTok{\}}
\NormalTok{rentaldata2b.omit =}\StringTok{ }\KeywordTok{na.omit}\NormalTok{(rentaldata2b)}
\KeywordTok{print}\NormalTok{(}\KeywordTok{head}\NormalTok{(rentaldata2b.omit, }\DecValTok{10}\NormalTok{))}

\KeywordTok{all}\NormalTok{(rentaldata2b.omit}\OperatorTok{$}\NormalTok{clrent }\OperatorTok{==}\StringTok{ }\NormalTok{rentaldata2b.omit}\OperatorTok{$}\NormalTok{clrent.calc)}
\NormalTok{rentaldata.omit =}\StringTok{ }\KeywordTok{na.omit}\NormalTok{(rentaldata)}
\NormalTok{rentaldata.omit =}\StringTok{ }
\StringTok{  }\NormalTok{rentaldata.omit }\OperatorTok{%>%}\StringTok{ }\KeywordTok{select}\NormalTok{(clrent, clpop, clavginc, cpctstu)}
\NormalTok{lm.modelc =}\StringTok{ }\KeywordTok{lm}\NormalTok{(clrent }\OperatorTok{~}\StringTok{ }\NormalTok{clpop }\OperatorTok{+}\StringTok{ }\NormalTok{clavginc }\OperatorTok{+}\StringTok{ }\NormalTok{cpctstu, }\DataTypeTok{data =}\NormalTok{ rentaldata.omit)}

\KeywordTok{summary}\NormalTok{(lm.modelc)}
\NormalTok{df3 =}\StringTok{ }\NormalTok{rentaldata.omit}
\NormalTok{df3}\FloatTok{.1}\NormalTok{ <-}\StringTok{ }\KeywordTok{cbind.data.frame}\NormalTok{(df3, lm.modelc}\OperatorTok{$}\NormalTok{residuals, lm.modelc}\OperatorTok{$}\NormalTok{fitted.values)}
\NormalTok{df3}\FloatTok{.1}\NormalTok{ <-}\StringTok{ }
\StringTok{  }\NormalTok{df3}\FloatTok{.1} \OperatorTok{%>%}\StringTok{ }\KeywordTok{arrange}\NormalTok{(}\StringTok{`}\DataTypeTok{lm.modelc$fitted.values}\StringTok{`}\NormalTok{)}
\NormalTok{df3}\FloatTok{.1}\OperatorTok{$}\NormalTok{Index <-}\StringTok{ }\DecValTok{1}\OperatorTok{:}\KeywordTok{nrow}\NormalTok{(df3}\FloatTok{.1}\NormalTok{)}
\NormalTok{df3}\FloatTok{.1}\NormalTok{ <-}\StringTok{ }
\StringTok{  }\NormalTok{df3}\FloatTok{.1} \OperatorTok{%>%}\StringTok{ }\KeywordTok{select}\NormalTok{(Index, }\StringTok{`}\DataTypeTok{lm.modelc$residuals}\StringTok{`}\NormalTok{)}
\KeywordTok{names}\NormalTok{(df3}\FloatTok{.1}\NormalTok{) =}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Index"}\NormalTok{, }\StringTok{"Residuals"}\NormalTok{)}
\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ df3}\FloatTok{.1}\NormalTok{, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ Index, }\DataTypeTok{y =}\NormalTok{ Residuals)) }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_point}\NormalTok{() }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{theme_clean}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_hline}\NormalTok{(}\DataTypeTok{yintercept =} \DecValTok{0}\NormalTok{, }\DataTypeTok{linetype =} \StringTok{"dashed"}\NormalTok{) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{scale_x_continuous}\NormalTok{(}\StringTok{""}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Residual Plot"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\end{document}
